[package]
name = "layerizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
fxhash = "0.2.1"
image = "0.25.5"
psd = "0.3.5"
rayon = "1.10.0"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
